clear
intBaseFS = 8000;
chrForC = 'F';
ltSound = [time(chrForC,5,0,4,intBaseFS),...
		 time(chrForC,0,0,0,intBaseFS),...
		 time(chrForC,5,0,8,intBaseFS),...
		 time(chrForC,0,0,0,intBaseFS),...
		 time(chrForC,6,0,8,intBaseFS),...
		 time(chrForC,0,0,0,intBaseFS),...
		 time(chrForC,2,0,2,intBaseFS),...
		 time(chrForC,0,0,0,intBaseFS),...
		 time(chrForC,1,0,4,intBaseFS),...
		 time(chrForC,0,0,0,intBaseFS),...
		 time(chrForC,1,0,8,intBaseFS),...
		 time(chrForC,0,0,0,intBaseFS),...
		 time(chrForC,6,-1,8,intBaseFS),...
		 time(chrForC,0,0,0,intBaseFS),...
		 time(chrForC,2,0,2,intBaseFS)];
ltSize = size(ltSound);
ltTime = [1:ltSize(2)]/intBaseFS;
ltFinalMusic = sin(2*pi*ltSound.*ltTime);
sound(ltFinalMusic);


